### ISSUE TITLE
Click Menu need jQuery

### ISSUE THREAD

**Issue by tigefa4u** [chris-brown/Masonry-Ghost-Theme#2]
awesome themes :+1: 
no result if click menu :confused:

[jQuery](https://github.com/TryGhost/Ghost/blob/master/PRIVACY.md#default-theme)

**Comment by chris-brown** [comment]
Hi @tigefa4u most burger menus are dependent upon javascript. But ive added a solution [here](https://github.com/chris-brown/Masonry-Ghost-Theme/commit/ccc4ba9ff6c5a4797342d21211ca7111d586d8a4) just pull down the latest and run gulp again.

Hope it makes sense. If you now turn javascript off then the menu will function.

**Comment by tigefa4u** [comment]
solved now
thanks. :heart_eyes:
