### ISSUE TITLE
ReferenceError: Can't find variable: jQuery

### ISSUE THREAD

**Issue by somenathghosh** [chris-brown/Masonry-Ghost-Theme#3]
Getting this error : ReferenceError: Can't find variable: jQuery. Please help.

**Comment by chris-brown** [comment]
looks as though the following issue https://github.com/TryGhost/Ghost/issues/5298 and this https://github.com/TryGhost/Ghost/commit/6c5fea40ca00e2084d98e42598bcb76cd21624ce has caused the error.

To fix please inject [jQuery CDN](https://developers.google.com/speed/libraries/#jquery) using the following documentation.

http://support.ghost.org/use-code-injection/

**Comment by chris-brown** [comment]
hi @somenathghosh this has now been fix. please refer to https://github.com/chris-brown/Masonry-Ghost-Theme/commit/7bee2add9d51610ee5809392e48659bbf5b5c5dc.

please pull the latest and it should work. let me how you go.
